app:
  name: contract_toolkit
  env: homlogacao

defaults:
  log:
    logpath: ./logs
    max_sizefile: 5
    bkp_count: 5
    loglevel: INFO
    console_display: True

services:
  coleta_contratos:
    client_id: user_id
    client_secret: user_secret
    url_token: auth_token_url
    input_path: entry/coleta_contratos.csv
    output_path: output/coleta_contratos.csv

  isenta_contratos:
    url_get: get_old_negociation_url
    url_put: put_new_negociation_url
    valor: 0
    input_path: entry/isenta_contratos.csv
    output_path: output/isenta_contratos.xlsx

  reativa_contratos:
    url_get_contrato: get_old_contract_url
    url_put_contrato: put_new_contract_url
    url_get_equip: get_old_equip_url
    url_put_equip: put_new_equip_url
    input_path: entry/reativa_contratos.csv
    output_path: output/reativa_contratos.xlsx

   massive_cancel:
    requests_url:
      url_get_contrato: url_get_contrato
      url_put_contrato: url_put_contrato
      url_get_contrato_equip: url_get_contrato_equip
      url_put_contrato_equip: url_put_contrato_equip
      url_get_neg: url_get_neg
      url_put_neg: url_put_neg
      url_get_protocol: url_get_protocol
      url_put_protocol: url_put_protocol
    paths:
      input_path: entry/massive_cancel.csv
      output_path: output/massive_cancel.xlsx

  massive_desc:
    requests_url:
      url_desc: url_desc
    paths:
      input_path: entry/massive_desc.csv
      output_path: output/massive_desc.xlsx