app:
  name: contract_toolkit
  env: homlogacao

defaults:
  log:
    logpath: ./logs
    max_sizefile: 5
    bkp_count: 5
    loglevel: INFO
    console_display: True

services:
  coleta_contratos:
    client_id: user_id
    client_secret: user_secret
    url_token: auth_token_url
    input_path: entry/coleta_contratos.csv
    output_path: output/coleta_contratos.csv

  isenta_contratos:
    url_get: get_old_negociation_url
    url_put: put_new_negociation_url
    valor: 0
    input_path: entry/isenta_contratos.csv
    output_path: output/isenta_contratos.xlsx

  reativa_contratos:
    url_get_contrato: get_old_contract_url
    url_put_contrato: put_new_contract_url
    url_get_equip: get_old_equip_url
    url_put_equip: put_new_equip_url
    input_path: entry/reativa_contratos.csv
    output_path: output/reativa_contratos.xlsx